### PR TITLE
fix: changed the crypto public key provider to Bouncy Castle

### LINKED ISSUE #222: Change crypto key provider
In order to enable the customer to store the public and private keys in their machine, consider switching to third party crypto key providers like Tink, Bouncy Castle etc.,

### PR DESCRIPTION
**Pull request by Sita04**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-security-private-ca/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #222 ☕️

### CODE REVIEW

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java [hunk 1]
```diff
@@ -77,24 +74,24 @@ public static void reqEnvVar(String envVarName) {
...
     CA_NAME_DELETE = "ca-name-" + UUID.randomUUID().toString();
     CERTIFICATE_NAME = "certificate-name-" + UUID.randomUUID().toString();
-    KEY_RING_ID = "key-ring-id-" + UUID.randomUUID().toString();
-    KEY_ID = "key-id-" + UUID.randomUUID().toString();
-    VERSION_ID = "1";
+    KEY_SIZE = 2048;
 
     // Create CA Pool.
     privateca.CreateCaPool.createCaPool(PROJECT_ID, LOCATION, CA_POOL_NAME);
     privateca.CreateCaPool.createCaPool(PROJECT_ID, LOCATION, CA_POOL_NAME_DELETE);
```
Comment (pmansour) [inline samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:93]: what is this used for?

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java [hunk 2]
```diff
@@ -138,73 +127,40 @@ public static void cleanUp() throws InterruptedException, ExecutionException, IO
...
-    }
-  }
-
   // Wait for the specified amount of time.
   public static void sleep(int seconds) throws InterruptedException {
     TimeUnit.SECONDS.sleep(seconds);
   }
 
+  // Create an asymmetric key pair to be used in certificate signing.
+  public static ByteString createPublicKey()
```
Comment (pmansour) [inline samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:136]: suggestion: change this method to something like `createPemEncodedKeyPair()`, and return both the private and public keys.

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java [hunk 3]
```diff
@@ -138,73 +127,40 @@ public static void cleanUp() throws InterruptedException, ExecutionException, IO
...
+    KeyPair keyPair = generator.generateKeyPair();
+    System.out.println("RSA key pair generated.");
+
+    // Only the public key will be used to create the certificate.
+    // Save the private key in your machine to verify the certificate.
+    RSAPrivateKey privateKey = (RSAPrivateKey) keyPair.getPrivate();
+    RSAPublicKey publicKey = (RSAPublicKey) keyPair.getPublic();
+
+    // Construct the PemObject for public key.
+    PemObject pemObject = new PemObject("RSA PUBLIC KEY", publicKey.getEncoded());
```
Comment (pmansour) [inline samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:152]: It's worth double checking whether the encoded public key will be in SPKI or PKCS#1 format. If SPKI, then I believe the most appropriate header here will be "PUBLIC KEY" rather than "RSA PUBLIC KEY". I couldn't easily confirm this with a quick search, so it might be worth exporting this to a file and using openssl to check the actual format.

https://datatracker.ietf.org/doc/html/rfc7468#section-13

See also the answers to this question: https://stackoverflow.com/q/18039401

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java (hunk 1 above)
Comment (pmansour) [reply samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:93]: (and same for CA_NAME_DELETE on line 102-103)

**Review by pmansour — COMMENTED** [review]
Thank you!

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java (hunk 1 above)
Comment (Sita04) [reply samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:93]: I wanted to specify the default key size as 2048, to maintain the standard value across our tests.

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java (hunk 2 above)
Comment (Sita04) [reply samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:136]: Thank you. That's a great way to demonstrate how to generate both public and private keys. 
Will modify it!

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java (hunk 1 above)
Comment (Sita04) [reply samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:93]: CA_NAME_DELETE is entirely required only for testing purposes as all the tests in this repo run concurrently.
Essentially, we perform create and delete test operations at the same time and hence would require more than one CA.

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java (hunk 3 above)
Comment (Sita04) [reply samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:152]: Thank you Peter for this great insight!
Bouncy Castle framework allows us the flexibility to choose the encoding format, be it PKCS#1 or SPKI etc., 

As per your suggestion, I tried encoding it in SPKI format, verified with openssl and also went ahead to create & check the validity of the issued cert and it works fine. Will update it in the following commit.

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java [hunk 4]
```diff
@@ -133,32 +143,43 @@ public static void sleep(int seconds) throws InterruptedException {
   }
 
   // Create an asymmetric key pair to be used in certificate signing.
-  public static ByteString createPublicKey()
+  public static Map.Entry createPemEncodedKeyPair()
```
Comment (pmansour) [inline samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:146]: This feels like a hacky use for Map.Entry since a) this isn't part of a map, b) this isn't a key-value pair, and most importantly c) it's not clear from the return type which part is the private key and which is the public key.

I would suggest simply returning the KeyPair from this method and pem-encoding it in the calling method above. This leaves a clear contract and makes it easy to follow which is the private vs. public key. The calling method seems to have to do some pem-encoding anyway so this would fit in nicely.

**Review by pmansour — APPROVED** [review]
Thanks Sita!

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java (hunk 1 above)
Comment (Sita04) [reply samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:93]: CA_POOL_NAME_DELETE is being used to test CA deletion. Kindly refer to line number 218-219.
This is essential to demonstrate the deletion behaviour.

Kindly let me know if you think this approach could be simplified in some other way! Thanks!

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java (hunk 4 above)
Comment (Sita04) [reply samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java]: I had an ambivalent emotion about exposing too much of BC framework in the setup, and hence had to take the less prettier way.
But I totally agree with your viewpoint.

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java (hunk 1 above)
Comment (pmansour) [reply samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:93]: ah I see, I didn't realize there were a bunch of tests at the bottom that exercise various code paths. Fair enough then, feel free to resolve =)

**Review by pmansour — APPROVED** [review]
Looks awesome, feel free to resolve all the threads I started :-)

File: samples/snippets/cloud-client/src/main/java/privateca/CreateCertificate.java [hunk 5]
```diff
@@ -74,7 +62,7 @@ public static void main(String[] args)
   }
 
   // Create a Certificate which is issued by the Certificate Authority present in the CA Pool.
-  // The key used to sign the certificate is created by the Cloud KMS.
+  // The public key used to sign the certificate can be generated using any crypto library/framework
```
Comment (telpirion) [inline samples/snippets/cloud-client/src/main/java/privateca/CreateCertificate.java:65]: NIT: Insert line break after "crypto".

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java [hunk 6]
```diff
@@ -105,17 +102,31 @@ public static void setUp() throws InterruptedException, ExecutionException, IOEx
     privateca.EnableCertificateAuthority.enableCertificateAuthority(
         PROJECT_ID, LOCATION, CA_POOL_NAME, CA_NAME);
 
-    // Create Asymmetric Sign Key used to sign certificate, with Cloud KMS.
-    createKeyRing();
-    sleep(5);
-    createAsymmetricSignKey();
+    System.out.println("Starting key creation with Bouncy Castle...");
```
Comment (telpirion) [inline samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:105]: I believe we typically try to avoid printing to `System.out` in an integration test.

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java [hunk 7]
```diff
@@ -105,17 +102,31 @@ public static void setUp() throws InterruptedException, ExecutionException, IOEx
...
 
-    // Retrieve public key from Cloud KMS and Create Certificate.
-    ByteString publicKey =
-        privateca.CreateCertificate.retrievePublicKey(
-            PROJECT_ID, KMS_LOCATION, KEY_RING_ID, KEY_ID, VERSION_ID);
+    // TODO (Developers): Save the private key by writing it to a file and
+    // TODO (cont): use it to verify the issued certificate.
+    ByteString privateKeyByteString = convertToPemEncodedByteString(privateKeyPemObject);
+
+    System.out.println("Key creation successful!");
```
Comment (telpirion) [inline samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java:125]: See above note; consider removing writing to console in test.

**Review by telpirion — APPROVED** [review]
Only small nits; LGTM!

File: samples/snippets/cloud-client/src/main/java/privateca/CreateCertificate.java (hunk 5 above)
Comment (Sita04) [reply samples/snippets/cloud-client/src/main/java/privateca/CreateCertificate.java]: Done!

File: samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java (hunk 6 above)
Comment (Sita04) [reply samples/snippets/cloud-client/src/test/java/privateca/SnippetsIT.java]: Done. thanks

**Comment by Sita04** [comment]
Thank you for the comments. Fixed those. PTAL @telpirion

**Review by telpirion — APPROVED** [review]

**Review by Neenu1995 — APPROVED** [review]
